### ISSUE TITLE
Add UI scaling

### ISSUE THREAD

**Issue by LFS6502** [kittybupu/openVCB#3]
![imagen](https://user-images.githubusercontent.com/29693543/203850640-775c0e07-526e-4858-93b1-5e26a0ade573.png)
The UI scale is too small when playing at high resolutions (3840x2160p in the image). The UI is too small to be used effectively.

Suggestion: A GUI scaling setting, it can be automatically changed depending on the resolution, or perhaps be exposed to the user.

**Comment by kittybupu** [comment]
Added in 0.8.9
